sudo: true
services:
  - docker
dist: trusty

# This travis build task expects following env to be set:
#
# DOCKER_USERNAME  - login to hub.docker.com
# DOCKER_PASSWORD  - password to hub.docker.com
# DOCKER_NAMESPACE - name spase on hub.docker.com (same as user name for private images)

env:
  - DOCKER_IMAGE=travis-odp-lng-x86 IMGDIR=x86_64
  - DOCKER_IMAGE=travis-odp-lng-ubuntu_14.04.05 IMGDIR=ubuntu_14.04.05
  - DOCKER_IMAGE=travis-odp-lng-ubuntu_14.04.05_i386 IMGDIR=ubuntu_14.04.05_i386

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t "$DOCKER_IMAGE" "$IMGDIR"
  - docker images
  - docker tag "$DOCKER_IMAGE" "$DOCKER_NAMESPACE/$DOCKER_IMAGE"
  - docker push "$DOCKER_NAMESPACE/$DOCKER_IMAGE"
